# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_processing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'image_processing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16image_processing.proto\"]\n\x0cImageRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x12\x11\n\toperation\x18\x03 \x01(\t\x12\x14\n\x0clamport_time\x18\x04 \x01(\x05\"G\n\nImageReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x12\x14\n\x0clamport_time\x18\x03 \x01(\x05\"|\n\x0c\x42lockRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x12\n\nimage_data\x18\x04 \x01(\x0c\x12\x11\n\toperation\x18\x05 \x01(\t\x12\x14\n\x0clamport_time\x18\x06 \x01(\x05\"z\n\nBlockReply\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x12\n\nimage_data\x18\x04 \x01(\x0c\x12\x11\n\tworker_id\x18\x05 \x01(\t\x12\x14\n\x0clamport_time\x18\x06 \x01(\x05\x32@\n\x12\x43oordinatorService\x12*\n\x0cProcessImage\x12\r.ImageRequest\x1a\x0b.ImageReply2;\n\rWorkerService\x12*\n\x0cProcessBlock\x12\r.BlockRequest\x1a\x0b.BlockReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=26
  _globals['_IMAGEREQUEST']._serialized_end=119
  _globals['_IMAGEREPLY']._serialized_start=121
  _globals['_IMAGEREPLY']._serialized_end=192
  _globals['_BLOCKREQUEST']._serialized_start=194
  _globals['_BLOCKREQUEST']._serialized_end=318
  _globals['_BLOCKREPLY']._serialized_start=320
  _globals['_BLOCKREPLY']._serialized_end=442
  _globals['_COORDINATORSERVICE']._serialized_start=444
  _globals['_COORDINATORSERVICE']._serialized_end=508
  _globals['_WORKERSERVICE']._serialized_start=510
  _globals['_WORKERSERVICE']._serialized_end=569
# @@protoc_insertion_point(module_scope)
